### ISSUE TITLE
Support for Firefox Web Extensions

### ISSUE THREAD

**Issue by ToggoStar** [kinitawowi/linkvisitor#4]
Hello!

First of all: Thank you very much for this awesome Add-On!

Unfortunately, it is no longer compatible with Firefox as they switched to the new Web Extension format. Are there any plans to update it? I myself unfortunately have no where the skill necessary... 

Cheers,
Martin

**Comment by kinitawowi** [comment]
Thanks for the heads up,  I've submitted a revised version for approval.
